package com.variant.server.boot

import com.variant.server.api.ServerException
import com.variant.core.error.ServerError

/**
 * Server exceptions that are generated by the foreground and which DO NOT have predefined
 * error constants in ServerError (core). These are basically internal assertion failures.
 *
 * @since 0.7
 */
case class ServerExceptionInternal(msg: String, t: Throwable) extends ServerException(msg, t) {

   def this(msg: String) = this(msg, null)

   def toRemoteException = ServerExceptionRemote(ServerError.InternalError, msg)
}

object ServerExceptionInternal {

   def apply(msg: String, t: Throwable) = new ServerExceptionInternal(msg, t)

   def apply(msg: String) = new ServerExceptionInternal(msg, null)

   def apply(t: Throwable) = new ServerExceptionInternal(null, t)

}
